#!/usr/bin/env bash

C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        printf "${C_GREEN}OK!${C_RESET}\n"
    else
        printf "${C_RED}NOK!${C_RESET}\n\n"
        echo -e "$output"
        exit 1
    fi
}

__run "1/3" "PHP Lint" "git diff --diff-filter=AM --name-only --cached  | grep \".php$\" | xargs -r php -l"
__run "2/3" "PHP CS Fixer" "git diff --diff-filter=AM --name-only --cached  | grep \".php$\" | PHP_CS_FIXER_IGNORE_ENV=1 xargs -r vendor/bin/php-cs-fixer check --config=.php-cs-fixer.dist.php"
__run "3/3" "PHPStan" "git diff --diff-filter=AM --name-only --cached  | grep \".php$\" | xargs -r vendor/bin/phpstan analyse --memory-limit 1G"